[features]
seeds = false
skip-lint = false
[programs.localnet]
xen_dao_voting = "Bms9RrHVikZ9PUAohfShePSKYPHeoDV5N7YdE66HN17x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/bubabubasconi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
