[features]
seeds = false
skip-lint = false

[programs.localnet]
xen_dao_voting = "7XcNV2hAtWFBb6y4YfSngsDyCLGes8LbFeVhUJNrxGt7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/bubabubasconi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"
members = ["programs/*"]

[workspace.programs.localnet.xen_dao_voting]
program_size = 2000000  # Increase this value as needed